using https

diff --git a/bigbluebutton-config/bin/bbb-conf b/bigbluebutton-config/bin/bbb-conf
--- a/bigbluebutton-config/bin/bbb-conf
+++ b/bigbluebutton-config/bin/bbb-conf
@@ -337,8 +337,8 @@ start_bigbluebutton () {
 
 
 	BBB_WEB=$(cat ${SERVLET_DIR}/bigbluebutton/WEB-INF/classes/bigbluebutton.properties | sed -n '/^bigbluebutton.web.serverURL/{s/.*\///;p}')
-        if ! wget http://$BBB_WEB/bigbluebutton/api -O - --quiet | grep -q SUCCESS; then
-                echo "Startup unsuccessful: could not connect to http://$BBB_WEB/bigbluebutton/api"
+        if ! wget https://$BBB_WEB/bigbluebutton/api -O - --quiet | grep -q SUCCESS; then
+                echo "Startup unsuccessful: could not connect to https://$BBB_WEB/bigbluebutton/api"
                 exit 1
 	fi
 
@@ -1287,10 +1287,10 @@ check_state() {
 	#
         BBB_WEB=$(cat ${SERVLET_DIR}/bigbluebutton/WEB-INF/classes/bigbluebutton.properties | sed -n '/^bigbluebutton.web.serverURL/{s/.*\///;p}')
  	check_no_value server_name /etc/nginx/sites-available/bigbluebutton $BBB_WEB
-	if ! wget http://$BBB_WEB/bigbluebutton/api -O - --quiet | grep -q SUCCESS; then 
+	if ! wget https://$BBB_WEB/bigbluebutton/api -O - --quiet | grep -q SUCCESS; then 
 		echo "# Error: Could not connect to the configured hostname/IP address"
 		echo "#"
-		echo "#    http://$BBB_WEB/"
+		echo "#    https://$BBB_WEB/"
 		echo "#"
 		echo "# If your BigBlueButton server is behind a firewall, see FAQ:"
 		echo "#"
